# Site settings
title: Dylan Cairns Portfolio 
email: spookycorridor@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Spookycorridor 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spookycorridor.github.io" # the base hostname & protocol for your site
twitter_username: spookycorridor
github_username:  spookycorridor

# Build settings
markdown: kramdown
